<?php

declare(strict_types=1);

return [
    'AFN' => [
            'currency'       => 'Afghani',
            'alphabeticCode' => 'AFN',
            'numericCode'    => 971,
            'minorUnit'      => 2,
        ],
    'EUR' => [
            'currency'       => 'Euro',
            'alphabeticCode' => 'EUR',
            'numericCode'    => 978,
            'minorUnit'      => 2,
        ],
    'ALL' => [
            'currency'       => 'Lek',
            'alphabeticCode' => 'ALL',
            'numericCode'    => 8,
            'minorUnit'      => 2,
        ],
    'DZD' => [
            'currency'       => 'Algerian Dinar',
            'alphabeticCode' => 'DZD',
            'numericCode'    => 12,
            'minorUnit'      => 2,
        ],
    'USD' => [
            'currency'       => 'US Dollar',
            'alphabeticCode' => 'USD',
            'numericCode'    => 840,
            'minorUnit'      => 2,
        ],
    'AOA' => [
            'currency'       => 'Kwanza',
            'alphabeticCode' => 'AOA',
            'numericCode'    => 973,
            'minorUnit'      => 2,
        ],
    'XCD' => [
            'currency'       => 'East Caribbean Dollar',
            'alphabeticCode' => 'XCD',
            'numericCode'    => 951,
            'minorUnit'      => 2,
        ],
    'ARS' => [
            'currency'       => 'Argentine Peso',
            'alphabeticCode' => 'ARS',
            'numericCode'    => 32,
            'minorUnit'      => 2,
        ],
    'AMD' => [
            'currency'       => 'Armenian Dram',
            'alphabeticCode' => 'AMD',
            'numericCode'    => 51,
            'minorUnit'      => 2,
        ],
    'AWG' => [
            'currency'       => 'Aruban Florin',
            'alphabeticCode' => 'AWG',
            'numericCode'    => 533,
            'minorUnit'      => 2,
        ],
    'AUD' => [
            'currency'       => 'Australian Dollar',
            'alphabeticCode' => 'AUD',
            'numericCode'    => 36,
            'minorUnit'      => 2,
        ],
    'AZN' => [
            'currency'       => 'Azerbaijan Manat',
            'alphabeticCode' => 'AZN',
            'numericCode'    => 944,
            'minorUnit'      => 2,
        ],
    'BSD' => [
            'currency'       => 'Bahamian Dollar',
            'alphabeticCode' => 'BSD',
            'numericCode'    => 44,
            'minorUnit'      => 2,
        ],
    'BHD' => [
            'currency'       => 'Bahraini Dinar',
            'alphabeticCode' => 'BHD',
            'numericCode'    => 48,
            'minorUnit'      => 3,
        ],
    'BDT' => [
            'currency'       => 'Taka',
            'alphabeticCode' => 'BDT',
            'numericCode'    => 50,
            'minorUnit'      => 2,
        ],
    'BBD' => [
            'currency'       => 'Barbados Dollar',
            'alphabeticCode' => 'BBD',
            'numericCode'    => 52,
            'minorUnit'      => 2,
        ],
    'BYN' => [
            'currency'       => 'Belarusian Ruble',
            'alphabeticCode' => 'BYN',
            'numericCode'    => 933,
            'minorUnit'      => 2,
        ],
    'BZD' => [
            'currency'       => 'Belize Dollar',
            'alphabeticCode' => 'BZD',
            'numericCode'    => 84,
            'minorUnit'      => 2,
        ],
    'XOF' => [
            'currency'       => 'CFA Franc BCEAO',
            'alphabeticCode' => 'XOF',
            'numericCode'    => 952,
            'minorUnit'      => 0,
        ],
    'BMD' => [
            'currency'       => 'Bermudian Dollar',
            'alphabeticCode' => 'BMD',
            'numericCode'    => 60,
            'minorUnit'      => 2,
        ],
    'INR' => [
            'currency'       => 'Indian Rupee',
            'alphabeticCode' => 'INR',
            'numericCode'    => 356,
            'minorUnit'      => 2,
        ],
    'BTN' => [
            'currency'       => 'Ngultrum',
            'alphabeticCode' => 'BTN',
            'numericCode'    => 64,
            'minorUnit'      => 2,
        ],
    'BOB' => [
            'currency'       => 'Boliviano',
            'alphabeticCode' => 'BOB',
            'numericCode'    => 68,
            'minorUnit'      => 2,
        ],
    'BOV' => [
            'currency'       => 'Mvdol',
            'alphabeticCode' => 'BOV',
            'numericCode'    => 984,
            'minorUnit'      => 2,
        ],
    'BAM' => [
            'alphabeticCode' => 'BAM',
            'currency'       => 'Convertible Mark',
            'minorUnit'      => 2,
            'numericCode'    => 977,
        ],
    'BWP' => [
            'alphabeticCode' => 'BWP',
            'currency'       => 'Pula',
            'minorUnit'      => 2,
            'numericCode'    => 72,
        ],
    'NOK' => [
            'alphabeticCode' => 'NOK',
            'currency'       => 'Norwegian Krone',
            'minorUnit'      => 2,
            'numericCode'    => 578,
        ],
    'BRL' => [
            'alphabeticCode' => 'BRL',
            'currency'       => 'Brazilian Real',
            'minorUnit'      => 2,
            'numericCode'    => 986,
        ],
    'BND' => [
            'alphabeticCode' => 'BND',
            'currency'       => 'Brunei Dollar',
            'minorUnit'      => 2,
            'numericCode'    => 96,
        ],
    'BGN' => [
        'currency'       => 'Bulgarian Lev',
            'alphabeticCode' => 'BGN',
            'numericCode'    => 975,
            'minorUnit'      => 2,
        ],
    'BIF' => [
            'currency'       => 'Burundi Franc',
            'alphabeticCode' => 'BIF',
            'numericCode'    => 108,
            'minorUnit'      => 0,
        ],
    'CVE' => [
            'currency'       => 'Cabo Verde Escudo',
            'alphabeticCode' => 'CVE',
            'numericCode'    => 132,
            'minorUnit'      => 2,
        ],
    'KHR' => [
            'currency'       => 'Riel',
            'alphabeticCode' => 'KHR',
            'numericCode'    => 116,
            'minorUnit'      => 2,
        ],
    'XAF' => [
            'currency'       => 'CFA Franc BEAC',
            'alphabeticCode' => 'XAF',
            'numericCode'    => 950,
            'minorUnit'      => 0,
        ],
    'CAD' => [
            'currency'       => 'Canadian Dollar',
            'alphabeticCode' => 'CAD',
            'numericCode'    => 124,
            'minorUnit'      => 2,
        ],
    'KYD' => [
            'currency'       => 'Cayman Islands Dollar',
            'alphabeticCode' => 'KYD',
            'numericCode'    => 136,
            'minorUnit'      => 2,
        ],
    'CLP' => [
            'currency'       => 'Chilean Peso',
            'alphabeticCode' => 'CLP',
            'numericCode'    => 152,
            'minorUnit'      => 0,
        ],
    'CLF' => [
            'currency'       => 'Unidad de Fomento',
            'alphabeticCode' => 'CLF',
            'numericCode'    => 990,
            'minorUnit'      => 4,
        ],
    'CNY' => [
            'currency'       => 'Yuan Renminbi',
            'alphabeticCode' => 'CNY',
            'numericCode'    => 156,
            'minorUnit'      => 2,
        ],
    'COP' => [
            'currency'       => 'Colombian Peso',
            'alphabeticCode' => 'COP',
            'numericCode'    => 170,
            'minorUnit'      => 2,
        ],
    'COU' => [
            'currency'       => 'Unidad de Valor Real',
            'alphabeticCode' => 'COU',
            'numericCode'    => 970,
            'minorUnit'      => 2,
        ],
    'KMF' => [
            'currency'       => 'Comorian Franc',
            'alphabeticCode' => 'KMF',
            'numericCode'    => 174,
            'minorUnit'      => 0,
        ],
    'CDF' => [
            'currency'       => 'Congolese Franc',
            'alphabeticCode' => 'CDF',
            'numericCode'    => 976,
            'minorUnit'      => 2,
        ],
    'NZD' => [
            'currency'       => 'New Zealand Dollar',
            'alphabeticCode' => 'NZD',
            'numericCode'    => 554,
            'minorUnit'      => 2,
        ],
    'CRC' => [
            'currency'       => 'Costa Rican Colon',
            'alphabeticCode' => 'CRC',
            'numericCode'    => 188,
            'minorUnit'      => 2,
        ],
    'HRK' => [
            'currency'       => 'Kuna',
            'alphabeticCode' => 'HRK',
            'numericCode'    => 191,
            'minorUnit'      => 2,
        ],
    'CUP' => [
            'currency'       => 'Cuban Peso',
            'alphabeticCode' => 'CUP',
            'numericCode'    => 192,
            'minorUnit'      => 2,
        ],
    'CUC' => [
            'currency'       => 'Peso Convertible',
            'alphabeticCode' => 'CUC',
            'numericCode'    => 931,
            'minorUnit'      => 2,
        ],
    'ANG' => [
            'currency'       => 'Netherlands Antillean Guilder',
            'alphabeticCode' => 'ANG',
            'numericCode'    => 532,
            'minorUnit'      => 2,
        ],
    'CZK' => [
            'currency'       => 'Czech Koruna',
            'alphabeticCode' => 'CZK',
            'numericCode'    => 203,
            'minorUnit'      => 2,
        ],
    'DKK' => [
            'currency'       => 'Danish Krone',
            'alphabeticCode' => 'DKK',
            'numericCode'    => 208,
            'minorUnit'      => 2,
        ],
    'DJF' => [
            'currency'       => 'Djibouti Franc',
            'alphabeticCode' => 'DJF',
            'numericCode'    => 262,
            'minorUnit'      => 0,
        ],
    'DOP' => [
            'currency'       => 'Dominican Peso',
            'alphabeticCode' => 'DOP',
            'numericCode'    => 214,
            'minorUnit'      => 2,
        ],
    'EGP' => [
            'currency'       => 'Egyptian Pound',
            'alphabeticCode' => 'EGP',
            'numericCode'    => 818,
            'minorUnit'      => 2,
        ],
    'SVC' => [
            'currency'       => 'El Salvador Colon',
            'alphabeticCode' => 'SVC',
            'numericCode'    => 222,
            'minorUnit'      => 2,
        ],
    'ERN' => [
            'currency'       => 'Nakfa',
            'alphabeticCode' => 'ERN',
            'numericCode'    => 232,
            'minorUnit'      => 2,
        ],
    'ETB' => [
            'currency'       => 'Ethiopian Birr',
            'alphabeticCode' => 'ETB',
            'numericCode'    => 230,
            'minorUnit'      => 2,
        ],
    'FKP' => [
            'currency'       => 'Falkland Islands Pound',
            'alphabeticCode' => 'FKP',
            'numericCode'    => 238,
            'minorUnit'      => 2,
        ],
    'FJD' => [
            'currency'       => 'Fiji Dollar',
            'alphabeticCode' => 'FJD',
            'numericCode'    => 242,
            'minorUnit'      => 2,
        ],
    'XPF' => [
            'currency'       => 'CFP Franc',
            'alphabeticCode' => 'XPF',
            'numericCode'    => 953,
            'minorUnit'      => 0,
        ],
    'GMD' => [
            'currency'       => 'Dalasi',
            'alphabeticCode' => 'GMD',
            'numericCode'    => 270,
            'minorUnit'      => 2,
        ],
    'GEL' => [
            'currency'       => 'Lari',
            'alphabeticCode' => 'GEL',
            'numericCode'    => 981,
            'minorUnit'      => 2,
        ],
    'GHS' => [
            'currency'       => 'Ghana Cedi',
            'alphabeticCode' => 'GHS',
            'numericCode'    => 936,
            'minorUnit'      => 2,
        ],
    'GIP' => [
            'currency'       => 'Gibraltar Pound',
            'alphabeticCode' => 'GIP',
            'numericCode'    => 292,
            'minorUnit'      => 2,
        ],
    'GTQ' => [
            'currency'       => 'Quetzal',
            'alphabeticCode' => 'GTQ',
            'numericCode'    => 320,
            'minorUnit'      => 2,
        ],
    'GBP' => [
            'currency'       => 'Pound Sterling',
            'alphabeticCode' => 'GBP',
            'numericCode'    => 826,
            'minorUnit'      => 2,
        ],
    'GNF' => [
            'currency'       => 'Guinean Franc',
            'alphabeticCode' => 'GNF',
            'numericCode'    => 324,
            'minorUnit'      => 0,
        ],
    'GYD' => [
            'currency'       => 'Guyana Dollar',
            'alphabeticCode' => 'GYD',
            'numericCode'    => 328,
            'minorUnit'      => 2,
        ],
    'HTG' => [
            'currency'       => 'Gourde',
            'alphabeticCode' => 'HTG',
            'numericCode'    => 332,
            'minorUnit'      => 2,
        ],
    'HNL' => [
            'currency'       => 'Lempira',
            'alphabeticCode' => 'HNL',
            'numericCode'    => 340,
            'minorUnit'      => 2,
        ],
    'HKD' => [
            'currency'       => 'Hong Kong Dollar',
            'alphabeticCode' => 'HKD',
            'numericCode'    => 344,
            'minorUnit'      => 2,
        ],
    'HUF' => [
            'currency'       => 'Forint',
            'alphabeticCode' => 'HUF',
            'numericCode'    => 348,
            'minorUnit'      => 2,
        ],
    'ISK' => [
            'currency'       => 'Iceland Krona',
            'alphabeticCode' => 'ISK',
            'numericCode'    => 352,
            'minorUnit'      => 0,
        ],
    'IDR' => [
            'currency'       => 'Rupiah',
            'alphabeticCode' => 'IDR',
            'numericCode'    => 360,
            'minorUnit'      => 2,
        ],
    'XDR' => [
            'currency'       => 'SDR (Special Drawing Right)',
            'alphabeticCode' => 'XDR',
            'numericCode'    => 960,
            'minorUnit'      => 0,
        ],
    'IRR' => [
            'currency'       => 'Iranian Rial',
            'alphabeticCode' => 'IRR',
            'numericCode'    => 364,
            'minorUnit'      => 2,
        ],
    'IQD' => [
            'currency'       => 'Iraqi Dinar',
            'alphabeticCode' => 'IQD',
            'numericCode'    => 368,
            'minorUnit'      => 3,
        ],
    'ILS' => [
            'currency'       => 'New Israeli Sheqel',
            'alphabeticCode' => 'ILS',
            'numericCode'    => 376,
            'minorUnit'      => 2,
        ],
    'JMD' => [
            'currency'       => 'Jamaican Dollar',
            'alphabeticCode' => 'JMD',
            'numericCode'    => 388,
            'minorUnit'      => 2,
        ],
    'JPY' => [
            'currency'       => 'Yen',
            'alphabeticCode' => 'JPY',
            'numericCode'    => 392,
            'minorUnit'      => 0,
        ],
    'JOD' => [
            'currency'       => 'Jordanian Dinar',
            'alphabeticCode' => 'JOD',
            'numericCode'    => 400,
            'minorUnit'      => 3,
        ],
    'KZT' => [
            'currency'       => 'Tenge',
            'alphabeticCode' => 'KZT',
            'numericCode'    => 398,
            'minorUnit'      => 2,
        ],
    'KES' => [
            'currency'       => 'Kenyan Shilling',
            'alphabeticCode' => 'KES',
            'numericCode'    => 404,
            'minorUnit'      => 2,
        ],
    'KPW' => [
            'currency'       => 'North Korean Won',
            'alphabeticCode' => 'KPW',
            'numericCode'    => 408,
            'minorUnit'      => 2,
        ],
    'KRW' => [
            'currency'       => 'Won',
            'alphabeticCode' => 'KRW',
            'numericCode'    => 410,
            'minorUnit'      => 0,
        ],
    'KWD' => [
            'currency'       => 'Kuwaiti Dinar',
            'alphabeticCode' => 'KWD',
            'numericCode'    => 414,
            'minorUnit'      => 3,
        ],
    'KGS' => [
            'currency'       => 'Som',
            'alphabeticCode' => 'KGS',
            'numericCode'    => 417,
            'minorUnit'      => 2,
        ],
    'LAK' => [
            'currency'       => 'Lao Kip',
            'alphabeticCode' => 'LAK',
            'numericCode'    => 418,
            'minorUnit'      => 2,
        ],
    'LBP' => [
            'currency'       => 'Lebanese Pound',
            'alphabeticCode' => 'LBP',
            'numericCode'    => 422,
            'minorUnit'      => 2,
        ],
    'LSL' => [
            'currency'       => 'Loti',
            'alphabeticCode' => 'LSL',
            'numericCode'    => 426,
            'minorUnit'      => 2,
        ],
    'ZAR' => [
            'currency'       => 'Rand',
            'alphabeticCode' => 'ZAR',
            'numericCode'    => 710,
            'minorUnit'      => 2,
        ],
    'LRD' => [
            'currency'       => 'Liberian Dollar',
            'alphabeticCode' => 'LRD',
            'numericCode'    => 430,
            'minorUnit'      => 2,
        ],
    'LYD' => [
            'currency'       => 'Libyan Dinar',
            'alphabeticCode' => 'LYD',
            'numericCode'    => 434,
            'minorUnit'      => 3,
        ],
    'CHF' => [
            'currency'       => 'Swiss Franc',
            'alphabeticCode' => 'CHF',
            'numericCode'    => 756,
            'minorUnit'      => 2,
        ],
    'MOP' => [
            'currency'       => 'Pataca',
            'alphabeticCode' => 'MOP',
            'numericCode'    => 446,
            'minorUnit'      => 2,
        ],
    'MKD' => [
            'currency'       => 'Denar',
            'alphabeticCode' => 'MKD',
            'numericCode'    => 807,
            'minorUnit'      => 2,
        ],
    'MGA' => [
            'currency'       => 'Malagasy Ariary',
            'alphabeticCode' => 'MGA',
            'numericCode'    => 969,
            'minorUnit'      => 2,
        ],
    'MWK' => [
            'currency'       => 'Malawi Kwacha',
            'alphabeticCode' => 'MWK',
            'numericCode'    => 454,
            'minorUnit'      => 2,
        ],
    'MYR' => [
            'currency'       => 'Malaysian Ringgit',
            'alphabeticCode' => 'MYR',
            'numericCode'    => 458,
            'minorUnit'      => 2,
        ],
    'MVR' => [
            'currency'       => 'Rufiyaa',
            'alphabeticCode' => 'MVR',
            'numericCode'    => 462,
            'minorUnit'      => 2,
        ],
    'MRU' => [
            'currency'       => 'Ouguiya',
            'alphabeticCode' => 'MRU',
            'numericCode'    => 929,
            'minorUnit'      => 2,
        ],
    'MUR' => [
            'currency'       => 'Mauritius Rupee',
            'alphabeticCode' => 'MUR',
            'numericCode'    => 480,
            'minorUnit'      => 2,
        ],
    'XUA' => [
            'currency'       => 'ADB Unit of Account',
            'alphabeticCode' => 'XUA',
            'numericCode'    => 965,
            'minorUnit'      => 0,
        ],
    'MXN' => [
            'currency'       => 'Mexican Peso',
            'alphabeticCode' => 'MXN',
            'numericCode'    => 484,
            'minorUnit'      => 2,
        ],
    'MXV' => [
            'currency'       => 'Mexican Unidad de Inversion (UDI)',
            'alphabeticCode' => 'MXV',
            'numericCode'    => 979,
            'minorUnit'      => 2,
        ],
    'MDL' => [
            'currency'       => 'Moldovan Leu',
            'alphabeticCode' => 'MDL',
            'numericCode'    => 498,
            'minorUnit'      => 2,
        ],
    'MNT' => [
            'currency'       => 'Tugrik',
            'alphabeticCode' => 'MNT',
            'numericCode'    => 496,
            'minorUnit'      => 2,
        ],
    'MAD' => [
            'currency'       => 'Moroccan Dirham',
            'alphabeticCode' => 'MAD',
            'numericCode'    => 504,
            'minorUnit'      => 2,
        ],
    'MZN' => [
            'currency'       => 'Mozambique Metical',
            'alphabeticCode' => 'MZN',
            'numericCode'    => 943,
            'minorUnit'      => 2,
        ],
    'MMK' => [
            'currency'       => 'Kyat',
            'alphabeticCode' => 'MMK',
            'numericCode'    => 104,
            'minorUnit'      => 2,
        ],
    'NAD' => [
            'currency'       => 'Namibia Dollar',
            'alphabeticCode' => 'NAD',
            'numericCode'    => 516,
            'minorUnit'      => 2,
        ],
    'NPR' => [
            'currency'       => 'Nepalese Rupee',
            'alphabeticCode' => 'NPR',
            'numericCode'    => 524,
            'minorUnit'      => 2,
        ],
    'NIO' => [
            'currency'       => 'Cordoba Oro',
            'alphabeticCode' => 'NIO',
            'numericCode'    => 558,
            'minorUnit'      => 2,
        ],
    'NGN' => [
            'currency'       => 'Naira',
            'alphabeticCode' => 'NGN',
            'numericCode'    => 566,
            'minorUnit'      => 2,
        ],
    'OMR' => [
            'currency'       => 'Rial Omani',
            'alphabeticCode' => 'OMR',
            'numericCode'    => 512,
            'minorUnit'      => 3,
        ],
    'PKR' => [
            'currency'       => 'Pakistan Rupee',
            'alphabeticCode' => 'PKR',
            'numericCode'    => 586,
            'minorUnit'      => 2,
        ],
    'PAB' => [
            'currency'       => 'Balboa',
            'alphabeticCode' => 'PAB',
            'numericCode'    => 590,
            'minorUnit'      => 2,
        ],
    'PGK' => [
            'currency'       => 'Kina',
            'alphabeticCode' => 'PGK',
            'numericCode'    => 598,
            'minorUnit'      => 2,
        ],
    'PYG' => [
            'currency'       => 'Guarani',
            'alphabeticCode' => 'PYG',
            'numericCode'    => 600,
            'minorUnit'      => 0,
        ],
    'PEN' => [
            'currency'       => 'Sol',
            'alphabeticCode' => 'PEN',
            'numericCode'    => 604,
            'minorUnit'      => 2,
        ],
    'PHP' => [
            'currency'       => 'Philippine Peso',
            'alphabeticCode' => 'PHP',
            'numericCode'    => 608,
            'minorUnit'      => 2,
        ],
    'PLN' => [
            'currency'       => 'Zloty',
            'alphabeticCode' => 'PLN',
            'numericCode'    => 985,
            'minorUnit'      => 2,
        ],
    'QAR' => [
            'currency'       => 'Qatari Rial',
            'alphabeticCode' => 'QAR',
            'numericCode'    => 634,
            'minorUnit'      => 2,
        ],
    'RON' => [
            'currency'       => 'Romanian Leu',
            'alphabeticCode' => 'RON',
            'numericCode'    => 946,
            'minorUnit'      => 2,
        ],
    'RUB' => [
            'currency'       => 'Russian Ruble',
            'alphabeticCode' => 'RUB',
            'numericCode'    => 643,
            'minorUnit'      => 2,
        ],
    'RWF' => [
            'currency'       => 'Rwanda Franc',
            'alphabeticCode' => 'RWF',
            'numericCode'    => 646,
            'minorUnit'      => 0,
        ],
    'SHP' => [
            'currency'       => 'Saint Helena Pound',
            'alphabeticCode' => 'SHP',
            'numericCode'    => 654,
            'minorUnit'      => 2,
        ],
    'WST' => [
            'currency'       => 'Tala',
            'alphabeticCode' => 'WST',
            'numericCode'    => 882,
            'minorUnit'      => 2,
        ],
    'STN' => [
            'currency'       => 'Dobra',
            'alphabeticCode' => 'STN',
            'numericCode'    => 930,
            'minorUnit'      => 2,
        ],
    'SAR' => [
            'currency'       => 'Saudi Riyal',
            'alphabeticCode' => 'SAR',
            'numericCode'    => 682,
            'minorUnit'      => 2,
        ],
    'RSD' => [
            'currency'       => 'Serbian Dinar',
            'alphabeticCode' => 'RSD',
            'numericCode'    => 941,
            'minorUnit'      => 2,
        ],
    'SCR' => [
            'currency'       => 'Seychelles Rupee',
            'alphabeticCode' => 'SCR',
            'numericCode'    => 690,
            'minorUnit'      => 2,
        ],
    'SLL' => [
            'currency'       => 'Leone',
            'alphabeticCode' => 'SLL',
            'numericCode'    => 694,
            'minorUnit'      => 2,
        ],
    'SGD' => [
            'currency'       => 'Singapore Dollar',
            'alphabeticCode' => 'SGD',
            'numericCode'    => 702,
            'minorUnit'      => 2,
        ],
    'XSU' => [
            'currency'       => 'Sucre',
            'alphabeticCode' => 'XSU',
            'numericCode'    => 994,
            'minorUnit'      => 0,
        ],
    'SBD' => [
            'currency'       => 'Solomon Islands Dollar',
            'alphabeticCode' => 'SBD',
            'numericCode'    => 90,
            'minorUnit'      => 2,
        ],
    'SOS' => [
            'currency'       => 'Somali Shilling',
            'alphabeticCode' => 'SOS',
            'numericCode'    => 706,
            'minorUnit'      => 2,
        ],
    'SSP' => [
            'currency'       => 'South Sudanese Pound',
            'alphabeticCode' => 'SSP',
            'numericCode'    => 728,
            'minorUnit'      => 2,
        ],
    'LKR' => [
            'currency'       => 'Sri Lanka Rupee',
            'alphabeticCode' => 'LKR',
            'numericCode'    => 144,
            'minorUnit'      => 2,
        ],
    'SDG' => [
            'currency'       => 'Sudanese Pound',
            'alphabeticCode' => 'SDG',
            'numericCode'    => 938,
            'minorUnit'      => 2,
        ],
    'SRD' => [
            'currency'       => 'Surinam Dollar',
            'alphabeticCode' => 'SRD',
            'numericCode'    => 968,
            'minorUnit'      => 2,
        ],
    'SZL' => [
            'currency'       => 'Lilangeni',
            'alphabeticCode' => 'SZL',
            'numericCode'    => 748,
            'minorUnit'      => 2,
        ],
    'SEK' => [
            'currency'       => 'Swedish Krona',
            'alphabeticCode' => 'SEK',
            'numericCode'    => 752,
            'minorUnit'      => 2,
        ],
    'CHE' => [
            'currency'       => 'WIR Euro',
            'alphabeticCode' => 'CHE',
            'numericCode'    => 947,
            'minorUnit'      => 2,
        ],
    'CHW' => [
            'currency'       => 'WIR Franc',
            'alphabeticCode' => 'CHW',
            'numericCode'    => 948,
            'minorUnit'      => 2,
        ],
    'SYP' => [
            'currency'       => 'Syrian Pound',
            'alphabeticCode' => 'SYP',
            'numericCode'    => 760,
            'minorUnit'      => 2,
        ],
    'TWD' => [
            'currency'       => 'New Taiwan Dollar',
            'alphabeticCode' => 'TWD',
            'numericCode'    => 901,
            'minorUnit'      => 2,
        ],
    'TJS' => [
            'currency'       => 'Somoni',
            'alphabeticCode' => 'TJS',
            'numericCode'    => 972,
            'minorUnit'      => 2,
        ],
    'TZS' => [
            'currency'       => 'Tanzanian Shilling',
            'alphabeticCode' => 'TZS',
            'numericCode'    => 834,
            'minorUnit'      => 2,
        ],
    'THB' => [
            'currency'       => 'Baht',
            'alphabeticCode' => 'THB',
            'numericCode'    => 764,
            'minorUnit'      => 2,
        ],
    'TOP' => [
            'currency'       => 'Pa’anga',
            'alphabeticCode' => 'TOP',
            'numericCode'    => 776,
            'minorUnit'      => 2,
        ],
    'TTD' => [
            'currency'       => 'Trinidad and Tobago Dollar',
            'alphabeticCode' => 'TTD',
            'numericCode'    => 780,
            'minorUnit'      => 2,
        ],
    'TND' => [
            'currency'       => 'Tunisian Dinar',
            'alphabeticCode' => 'TND',
            'numericCode'    => 788,
            'minorUnit'      => 3,
        ],
    'TRY' => [
            'currency'       => 'Turkish Lira',
            'alphabeticCode' => 'TRY',
            'numericCode'    => 949,
            'minorUnit'      => 2,
        ],
    'TMT' => [
            'currency'       => 'Turkmenistan New Manat',
            'alphabeticCode' => 'TMT',
            'numericCode'    => 934,
            'minorUnit'      => 2,
        ],
    'UGX' => [
            'currency'       => 'Uganda Shilling',
            'alphabeticCode' => 'UGX',
            'numericCode'    => 800,
            'minorUnit'      => 0,
        ],
    'UAH' => [
            'currency'       => 'Hryvnia',
            'alphabeticCode' => 'UAH',
            'numericCode'    => 980,
            'minorUnit'      => 2,
        ],
    'AED' => [
            'currency'       => 'UAE Dirham',
            'alphabeticCode' => 'AED',
            'numericCode'    => 784,
            'minorUnit'      => 2,
        ],
    'USN' => [
            'currency'       => 'US Dollar (Next day)',
            'alphabeticCode' => 'USN',
            'numericCode'    => 997,
            'minorUnit'      => 2,
        ],
    'UYU' => [
            'currency'       => 'Peso Uruguayo',
            'alphabeticCode' => 'UYU',
            'numericCode'    => 858,
            'minorUnit'      => 2,
        ],
    'UYI' => [
            'currency'       => 'Uruguay Peso en Unidades Indexadas (UI)',
            'alphabeticCode' => 'UYI',
            'numericCode'    => 940,
            'minorUnit'      => 0,
        ],
    'UZS' => [
            'currency'       => 'Uzbekistan Sum',
            'alphabeticCode' => 'UZS',
            'numericCode'    => 860,
            'minorUnit'      => 2,
        ],
    'VUV' => [
            'currency'       => 'Vatu',
            'alphabeticCode' => 'VUV',
            'numericCode'    => 548,
            'minorUnit'      => 0,
        ],
    'VEF' => [
            'currency'       => 'Bolívar',
            'alphabeticCode' => 'VEF',
            'numericCode'    => 937,
            'minorUnit'      => 2,
        ],
    'VND' => [
            'currency'       => 'Dong',
            'alphabeticCode' => 'VND',
            'numericCode'    => 704,
            'minorUnit'      => 0,
        ],
    'YER' => [
            'currency'       => 'Yemeni Rial',
            'alphabeticCode' => 'YER',
            'numericCode'    => 886,
            'minorUnit'      => 2,
        ],
    'ZMW' => [
            'currency'       => 'Zambian Kwacha',
            'alphabeticCode' => 'ZMW',
            'numericCode'    => 967,
            'minorUnit'      => 2,
        ],
    'ZWL' => [
            'currency'       => 'Zimbabwe Dollar',
            'alphabeticCode' => 'ZWL',
            'numericCode'    => 932,
            'minorUnit'      => 2,
        ],
    'XBA' => [
            'currency'       => 'Bond Markets Unit European Composite Unit (EURCO)',
            'alphabeticCode' => 'XBA',
            'numericCode'    => 955,
            'minorUnit'      => 0,
        ],
    'XBB' => [
            'currency'       => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
            'alphabeticCode' => 'XBB',
            'numericCode'    => 956,
            'minorUnit'      => 0,
        ],
    'XBC' => [
            'currency'       => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
            'alphabeticCode' => 'XBC',
            'numericCode'    => 957,
            'minorUnit'      => 0,
        ],
    'XBD' => [
            'currency'       => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
            'alphabeticCode' => 'XBD',
            'numericCode'    => 958,
            'minorUnit'      => 0,
        ],
    'XTS' => [
            'currency'       => 'Codes specifically reserved for testing purposes',
            'alphabeticCode' => 'XTS',
            'numericCode'    => 963,
            'minorUnit'      => 0,
        ],
    'XXX' => [
            'currency'       => 'The codes assigned for transactions where no currency is involved',
            'alphabeticCode' => 'XXX',
            'numericCode'    => 999,
            'minorUnit'      => 0,
        ],
    'XAU' => [
            'currency'       => 'Gold',
            'alphabeticCode' => 'XAU',
            'numericCode'    => 959,
            'minorUnit'      => 0,
        ],
    'XPD' => [
            'currency'       => 'Palladium',
            'alphabeticCode' => 'XPD',
            'numericCode'    => 964,
            'minorUnit'      => 0,
        ],
    'XPT' => [
            'currency'       => 'Platinum',
            'alphabeticCode' => 'XPT',
            'numericCode'    => 962,
            'minorUnit'      => 0,
        ],
    'XAG' => [
            'currency'       => 'Silver',
            'alphabeticCode' => 'XAG',
            'numericCode'    => 961,
            'minorUnit'      => 0,
        ],
];
